### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by irontom10** [vivalchemy/hyprhaven#1]
Debian does not ship with ripgrep installed. it must be installed manually for the script to function.

**Comment by vivianludrick** [comment]
So what do you say do I make it optional in the script it self or abort the script after suggesting to install it.

**Comment by irontom10** [comment]
I'd say just list them on the github page. If you want me to I'll go back trough and make sure it is just ripgrep.

**Comment by irontom10** [comment]
Best I can tell the requirements are ripgrep, curl, and libnotify-bin.
